kind: Pod
apiVersion: v1
metadata:
  name: mc-server-pod-java
  labels: 
    app: java
spec:
  volumes:
    - name: mc-world-storage
      persistentVolumeClaim:
        claimName: mc-claim-java
  containers:
    - name: mc-server-container-java
      image: ${DOCKER_REPO}
      ports:
        - containerPort: 25565
          name: "mc-server"
      volumeMounts:
        - mountPath: "/data"
          name: mc-world-storage
      env:
      - name: EULA
        value: "true"
      - name: VERSION
        value: ${RELEASE}
      - name: TYPE
        value: ${SERVERTYPE}
      - name: FTB_SERVER_MOD
        value: ${MODPACK}

---

apiVersion: v1
kind: Service
metadata:
  name: mc-exposer-java
  labels:
    app: java
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  selector: 
    app: java
